### ISSUE TITLE
more awesome?

### ISSUE THREAD

**Issue by tomByrer** [vigneshshanmugam/awesome-http2#1]
Unfortunately, there are already [more](https://github.com/http2/http2-spec/wiki/Implementations) awesome http2 [tool lists](https://github.com/http2/http2-spec/wiki/Tools).  I would recommend their list be the main hub for tools, since they are the working group.

However, there is a need for a meta-list of articles, training, CDNs & major hosts that support HTTP2, etc.  Since you started your list before I had this idea, I want to respect that & ask if you would prefer to maintain that list here or should I?

**Comment by vigneshshanmugam** [comment]
Sure would add them to the list. PR welcome :)
